### ISSUE TITLE
Unable to set highlightTheme in markdowns yaml front matter

### ISSUE THREAD

**Issue by Zachu** [webpro/reveal-md#186]
Hi!

I'm not sure if this is supposed to work but something made me think it should :)

I have this set up in the first part of the markdown I'm presenting:
```yaml
---
title: MyTitle
theme: league
highlightTheme: monokai
revealOptions:
    transition: 'convex'
    width: 1920
    height: 1080
    slideNumber: 'c/t'
---
```

All the other options do seem to work just as I'm expecting to, but the highlightTheme does nothing.

I am able to change the highlight theme from command line by starting the presentation with `--highlight-theme monokai`

I'm using the latest release candidate

```sh
$ reveal-md --version
2.0.0-rc.5
```

Thanks already! I'm just trying out reveal-md first time in the wild but it instantly made its way as my favorite presentation tool :)
