### ISSUE TITLE
Speaker notes do not become visible with `showNotes: true`

### ISSUE THREAD

**Issue by y0va** [webpro/reveal-md#203]
Following https://github.com/hakimel/reveal.js#share-and-print-speaker-notes I've set the option in the header:
```markdown
---
title: Blabla
description: Blablabla
showNotes: true
---
```

But the notes stay invisible in the printout using `--print` and in the browser.

**Comment by webpro** [comment]
You should use a `revealOptions` object to pass options to reveal.js (see https://github.com/webpro/reveal-md#yaml-front-matter for an example).

**Comment by y0va** [comment]
Ah ok! Thank you!

**Comment by ekliptik** [comment]
This doesn't work, could you provide a working example? 
```yml
---
title: Borked presentation
showNotes: true
revealOptions:
  transition: 'fade'
  plugins:
    - 'RevealMarkdown'
---
```
This produces a blank presentation with the correct number of slides.
