### ISSUE TITLE
Can you provide the Settings that can be filled in yaml formatter markdown head?

### ISSUE THREAD

**Issue by jackyliu16** [webpro/reveal-md#437]
It looks like not all of the pieces have been covered, for example seem the `--theme=black` in cil is match to `theme: black` in the head of md file, but seem `--highlight-theme: github` haven't a kind of shows in yaml formatter head of markdown

**Comment by ChongChengAC** [comment]
Maybe you're talking about `highlightTheme`?

This is my YAML in the head of markdown file. It specifies title, theme, highlight theme, and reveal.js options:
```yaml
---
title: reveal-md – The Markdown Presentation Framework
theme: black
highlightTheme: vs2015
revealOptions:
  transition: 'convex'
---
```
